version: '3.8'

services:
  frontend:
    build: 
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://backend:3001
    networks:
      - app-network

  backend:
    build: 
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./back:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DATABASE_URL=mysql://alex:alex123@db:3306/docker
      - DB_HOST=db
      - DB_USER=alex
      - DB_PASSWORD=alex123
      - DB_NAME=docker
      - PORT=3001
      - NODE_ENV=development
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --bind-address=0.0.0.0
      - --init-file=/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: alex123
      MYSQL_DATABASE: docker
      MYSQL_USER: alex
      MYSQL_PASSWORD: alex123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    name: mysql_data_housing